version: "3"
services:
  app:
    image: example
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - VITE_LOCALE=vi
      - VITE_NODE_ENV=development
    container_name: example
    ports:
      - 80:80
